version: '3.1'

services:
  # MySQL
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  # MySQL data
  mysql_db_data:


